[LIME-1192] Upgrade to aws-sdk V3
govuk-one-login/ipv-cri-dl-front pull request #286
Opened 2024-09-18 08:47 UTC by SarahHillGDS

## Proposed changes
Upgrade aws-sdk V2 to V3 as AWS SDK for JavaScript v2 entered maintenance mode on September 8, 2024.

### What changed

Upgraded aws-sdk in package.json to V3.
Dynamo session config and app.test were updated to reflect the V3 format

### Why did it change

### Issue tracking

- [LIME-1192](https://govukverify.atlassian.net/browse/LIME-1192)

### Other considerations

2024-09-18 10:08 UTC, smsgds requested changes

2024-09-18 10:08 UTC, smsgds commented on package.json
> +    "@aws-sdk/client-dynamodb": "^3.651.1",
Same as the fraud pr pin to a version

2024-09-19 09:14 UTC, ElliotMurphyGDS approved these changes

2024-09-19 09:23 UTC, SarahHillGDS commented on package.json
> +    "@aws-sdk/client-dynamodb": "^3.651.1",
resolved

2024-09-19 09:28 UTC, smsgds approved these changes

2024-09-20 14:34 UTC, smsgds approved these changes

2024-09-20 15:10 UTC, merged